# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpLogProxy < Formula
  desc "a web logging proxy for MCP client-server communication"
  homepage "https://github.com/emicklei/mcp-log-proxy"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/emicklei/mcp-log-proxy/releases/download/v0.2.5/mcp-log-proxy_Darwin_x86_64.tar.gz"
      sha256 "2a57e845c3fbebb905fe2919f3a466976244becd875061768bdc72bdafcef27f"

      def install
        bin.install "mcp-log-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/emicklei/mcp-log-proxy/releases/download/v0.2.5/mcp-log-proxy_Darwin_arm64.tar.gz"
      sha256 "bf1808a862202fa999a4c2773bf0abccd0f986ff7b2a438ccd20d80400bacbd2"

      def install
        bin.install "mcp-log-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/emicklei/mcp-log-proxy/releases/download/v0.2.5/mcp-log-proxy_Linux_x86_64.tar.gz"
      sha256 "504269a3b7208b285c9fc5b62c6ef2f6dfe71e63bdc90f6b4af2fda27ac1a8c7"
      def install
        bin.install "mcp-log-proxy"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/emicklei/mcp-log-proxy/releases/download/v0.2.5/mcp-log-proxy_Linux_arm64.tar.gz"
      sha256 "e0e1802138200a4654532dee74824aca8c8965b5056fcd07e0b7883d5087d563"
      def install
        bin.install "mcp-log-proxy"
      end
    end
  end
end
